using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MVC.WebUI.Entity
{
    public class DataInitializer : DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {

            var kategoriler = new List<Category>()
            {
                new Category(){Name = "Monitor", Description= "Monitor products"},
                new Category(){Name = "Processor", Description="Processor products"},
                new Category(){Name = "Display Card", Description="Display Card products"},
                new Category(){Name = "Ram", Description="Ram products"},
                new Category(){Name = "Motherboard", Description="Motherboard products"},
                new Category(){Name = "Ssd Storage", Description="Ssd Storage products"},
                new Category(){Name = "Hdd Storage", Description="Hdd Storage products"},
                new Category(){Name = "Computer cooler", Description="Cooling products"},
                new Category(){Name = "Power supply", Description="Power supply products"},
                new Category(){Name = "Computer tower", Description="Computer case products"},
                new Category(){Name = "Mouse", Description="Mouse products"},
                new Category(){Name = "Keyboard", Description="Keyboard products"},
            };


            foreach (var katogori in kategoriler)
            {
                context.Categories.Add(katogori);
            }
            context.SaveChanges();

            var urunler = new List<Product>
        {
            new Product(){Name = "Asus 144Hz Monitor", Description = "Profesyonel oyuncular ve etkileyici bir oyun deneyimi arayanlar için tasarlanan, 144 Hz yenileme hızına sahip 27 inç Full HD (1920x1080) 1500R oyuncu monitörüASUS Çok Düşük Hareket Bulanıklığı (ELMB™) teknolojisi 1 ms tepki süresi (MPRT) ile Adaptive-sync özelliğini birlikte sunarak gölgelenme ve yırtılma etkilerini ortadan kaldırıyor, yüksek kare hızlarında net oyun görüntüleri sunar.Ekran yırtılmalarını ve değişken kare hızlarını ortadan kaldıran FreeSync™ teknolojisi yer alır.Kendi ekseninde dönme, öne arkaya eğilme ve yükseklik ayarı olanakları sunan ergonomik tasarımlı bir stant bulunur", Price =500 , Stock =100 , IsApproved =false , CategoryId = 1,  Image="1.jpg"},
            new Product(){Name = "Asus 165Hz Monitor", Description = "Profesyonel oyuncular ve etkileyici bir oyun deneyimi arayanlar için tasarlanan, 165 Hz yenileme hızına sahip 24 inç Full HD (1920x1080) 1500R oyuncu monitörüASUS Çok Düşük Hareket Bulanıklığı (ELMB™) teknolojisi 1 ms tepki süresi (MPRT) ile Adaptive-sync özelliğini birlikte sunarak gölgelenme ve yırtılma etkilerini ortadan kaldırıyor, yüksek kare hızlarında net oyun görüntüleri sunar.Ekran yırtılmalarını ve değişken kare hızlarını ortadan kaldıran FreeSync™ teknolojisi yer alır.Kendi ekseninde dönme, öne arkaya eğilme ve yükseklik ayarı olanakları sunan ergonomik tasarımlı bir stant bulunur", Price =600 , Stock =100 , IsApproved =true , CategoryId = 1, Image="2.jpg"},
            new Product(){Name = "Asus 240Hz Monitor", Description = "Profesyonel oyuncular ve etkileyici bir oyun deneyimi arayanlar için tasarlanan, 240 Hz yenileme hızına sahip 27 inç Full HD (1920x1080) 1500R oyuncu monitörüASUS Çok Düşük Hareket Bulanıklığı (ELMB™) teknolojisi 1 ms tepki süresi (MPRT) ile Adaptive-sync özelliğini birlikte sunarak gölgelenme ve yırtılma etkilerini ortadan kaldırıyor, yüksek kare hızlarında net oyun görüntüleri sunar.Ekran yırtılmalarını ve değişken kare hızlarını ortadan kaldıran FreeSync™ teknolojisi yer alır.Kendi ekseninde dönme, öne arkaya eğilme ve yükseklik ayarı olanakları sunan ergonomik tasarımlı bir stant bulunur", Price = 1100, Stock =100 , IsApproved =true , CategoryId = 1, IsHome=true, Image="3.jpg" },
            new Product(){Name = "Msi 165Hz Monitor", Description = "Profesyonel oyuncular ve etkileyici bir oyun deneyimi arayanlar için tasarlanan, 165 Hz yenileme hızına sahip 27 inç Full HD (1920x1080) 1500R oyuncu monitörüASUS Çok Düşük Hareket Bulanıklığı (ELMB™) teknolojisi 1 ms tepki süresi (MPRT) ile Adaptive-sync özelliğini birlikte sunarak gölgelenme ve yırtılma etkilerini ortadan kaldırıyor, yüksek kare hızlarında net oyun görüntüleri sunar.Ekran yırtılmalarını ve değişken kare hızlarını ortadan kaldıran FreeSync™ teknolojisi yer alır.Kendi ekseninde dönme, öne arkaya eğilme ve yükseklik ayarı olanakları sunan ergonomik tasarımlı bir stant bulunur", Price = 750, Stock =100 , IsApproved =true , CategoryId = 1, Image="4.jpg" },
            new Product(){Name = "Msi 240Hz Monitor", Description = "Profesyonel oyuncular ve etkileyici bir oyun deneyimi arayanlar için tasarlanan, 240 Hz yenileme hızına sahip 27 inç Full HD (1920x1080) 1500R oyuncu monitörüASUS Çok Düşük Hareket Bulanıklığı (ELMB™) teknolojisi 1 ms tepki süresi (MPRT) ile Adaptive-sync özelliğini birlikte sunarak gölgelenme ve yırtılma etkilerini ortadan kaldırıyor, yüksek kare hızlarında net oyun görüntüleri sunar.Ekran yırtılmalarını ve değişken kare hızlarını ortadan kaldıran FreeSync™ teknolojisi yer alır.Kendi ekseninde dönme, öne arkaya eğilme ve yükseklik ayarı olanakları sunan ergonomik tasarımlı bir stant bulunur", Price = 1200, Stock =100 , IsApproved =true , CategoryId = 1, Image="5.jpg" },



            new Product() { Name = "Intel® Core™ i3-12600K Processor", Description = "Tavizsiz oyun deneyimi. 12. Nesil Intel® Core™ işlemcinin hibrit performans mimarisi, sekiz adede kadar Performans çekirdeği (P-çekirdek) ve sekiz adede kadar Verimlilik çekirdeği (E-çekirdek) içerir. İş yükleri de Intel® Thread Director tarafından akıllıca yönlendirilir.2 Yani o böler, siz yönetirsiniz.", Price =400 , Stock =500 , IsApproved = true, CategoryId = 2, Image="6.jpg" },
            new Product() { Name = "Intel® Core™ i5-12600K Processor", Description = "Tavizsiz oyun deneyimi. 12. Nesil Intel® Core™ işlemcinin hibrit performans mimarisi, sekiz adede kadar Performans çekirdeği (P-çekirdek) ve sekiz adede kadar Verimlilik çekirdeği (E-çekirdek) içerir. İş yükleri de Intel® Thread Director tarafından akıllıca yönlendirilir.2 Yani o böler, siz yönetirsiniz.", Price =500 , Stock =500 , IsApproved = true, CategoryId = 2, Image="7.jpg" },
            new Product() { Name = "Intel® Core™ i7-12600K Processor", Description = "Tavizsiz oyun deneyimi. 12. Nesil Intel® Core™ işlemcinin hibrit performans mimarisi, sekiz adede kadar Performans çekirdeği (P-çekirdek) ve sekiz adede kadar Verimlilik çekirdeği (E-çekirdek) içerir. İş yükleri de Intel® Thread Director tarafından akıllıca yönlendirilir.2 Yani o böler, siz yönetirsiniz.", Price =600 , Stock =500 , IsApproved = true, CategoryId = 2, Image="8.jpg" },
            new Product() { Name = "Intel® Core™ i9-12600K Processor", Description = "Tavizsiz oyun deneyimi. 12. Nesil Intel® Core™ işlemcinin hibrit performans mimarisi, sekiz adede kadar Performans çekirdeği (P-çekirdek) ve sekiz adede kadar Verimlilik çekirdeği (E-çekirdek) içerir. İş yükleri de Intel® Thread Director tarafından akıllıca yönlendirilir.2 Yani o böler, siz yönetirsiniz.", Price =1000 , Stock =500 , IsApproved = true, CategoryId = 2, IsHome = true, Image="9.jpg" },
            new Product() { Name = "Intel Core i9-13900K Processor", Description = "Tavizsiz oyun deneyimi. 13. Nesil Intel® Core™ işlemcinin hibrit performans mimarisi, sekiz adede kadar Performans çekirdeği (P-çekirdek) ve sekiz adede kadar Verimlilik çekirdeği (E-çekirdek) içerir. İş yükleri de Intel® Thread Director tarafından akıllıca yönlendirilir.2 Yani o böler, siz yönetirsiniz.", Price =2000, Stock =500 , IsApproved = true, CategoryId = 2, Image="10.jpg" },


            new Product() { Name = "Asus Tuf Rtx 3050 Display Card", Description = "Asus’ın ikonik Tuf Gaming serisi bir kez daha oyuncuların tanıyıp güvendikleri performans, düşük gürültü, verimlilik ve estetiği bir araya getiriyor. Artık siz de tüm favori oyunlarınızı serin tutan ve sessiz kalan güçlü ekran kartları oynayabilirsiniz. Tam istediğiniz gibi!", Price =1000 , Stock =500 , IsApproved = true, CategoryId = 3, Image="11.jpg" },
            new Product() { Name = "Asus Tuf Rtx 3060Ti Display Card", Description = "Asus’ın ikonik Tuf Gaming serisi bir kez daha oyuncuların tanıyıp güvendikleri performans, düşük gürültü, verimlilik ve estetiği bir araya getiriyor. Artık siz de tüm favori oyunlarınızı serin tutan ve sessiz kalan güçlü ekran kartları oynayabilirsiniz. Tam istediğiniz gibi!", Price =1500 , Stock =500 , IsApproved = true, CategoryId = 3, Image="12.jpg" },
            new Product() { Name = "Asus Tuf Rtx 3070Ti Display Card", Description = "Asus’ın ikonik Tuf Gaming serisi bir kez daha oyuncuların tanıyıp güvendikleri performans, düşük gürültü, verimlilik ve estetiği bir araya getiriyor. Artık siz de tüm favori oyunlarınızı serin tutan ve sessiz kalan güçlü ekran kartları oynayabilirsiniz. Tam istediğiniz gibi!", Price =1700 , Stock =500 , IsApproved = true, CategoryId = 3, Image="13.jpg" },
            new Product() { Name = "Asus Tuf Rtx 3080Ti Display Card", Description = "Asus’ın ikonik Tuf Gaming serisi bir kez daha oyuncuların tanıyıp güvendikleri performans, düşük gürültü, verimlilik ve estetiği bir araya getiriyor. Artık siz de tüm favori oyunlarınızı serin tutan ve sessiz kalan güçlü ekran kartları oynayabilirsiniz. Tam istediğiniz gibi!", Price =2500 , Stock =500 , IsApproved = true, CategoryId = 3, IsHome = true, Image="14.jpg" },
            new Product() { Name = "Asus Tuf Rtx 3090 Display Card", Description = "Asus’ın ikonik Tuf Gaming serisi bir kez daha oyuncuların tanıyıp güvendikleri performans, düşük gürültü, verimlilik ve estetiği bir araya getiriyor. Artık siz de tüm favori oyunlarınızı serin tutan ve sessiz kalan güçlü ekran kartları oynayabilirsiniz. Tam istediğiniz gibi!", Price =4000 , Stock =500 , IsApproved = true, CategoryId = 3, Image="15.jpg" },



            new Product() { Name = "Corsair (8x1) Ram", Description = "3200Mz Cl 16 Vengeance LPX DDR bellek serisi yüksek performanslı overclock için tasarlanmıştır. DR4 bellekler yüksek hız yanında düşük güç tüketimi ön plana çıkıyor. Asus, MSI, ASRock, Gigabyte gibi anakart üreticilerinin test edip onay verdiği yeni seriler XMP 2.0 profili içeriyor. Böylece kullanıcılar zamanlama, voltaj, frekans ayarlarını kolayca girebiliyor. Saf alüminyumdan yapılmış ısı dağıtıcısı daha hızlı ısı dağılımı sağlarken sekiz-katmanlı PCB ısıyı yönetmeye yardımcı olur ve üstün overclock imkanı tanır.", Price =50 , Stock =500 , IsApproved = true, CategoryId = 4, Image="16.jpg" },
            new Product() { Name = "Corsair (8x2) Ram", Description = "3200Mz Cl 16 Vengeance LPX DDR bellek serisi yüksek performanslı overclock için tasarlanmıştır. DR4 bellekler yüksek hız yanında düşük güç tüketimi ön plana çıkıyor. Asus, MSI, ASRock, Gigabyte gibi anakart üreticilerinin test edip onay verdiği yeni seriler XMP 2.0 profili içeriyor. Böylece kullanıcılar zamanlama, voltaj, frekans ayarlarını kolayca girebiliyor. Saf alüminyumdan yapılmış ısı dağıtıcısı daha hızlı ısı dağılımı sağlarken sekiz-katmanlı PCB ısıyı yönetmeye yardımcı olur ve üstün overclock imkanı tanır.", Price =80 , Stock =500 , IsApproved = true, CategoryId = 4, IsHome = true, Image="17.jpg" },
            new Product() { Name = "Corsair (16x2) Ram", Description = "4000Mz Cl 16 Vengeance LPX DDR bellek serisi yüksek performanslı overclock için tasarlanmıştır. DR4 bellekler yüksek hız yanında düşük güç tüketimi ön plana çıkıyor. Asus, MSI, ASRock, Gigabyte gibi anakart üreticilerinin test edip onay verdiği yeni seriler XMP 2.0 profili içeriyor. Böylece kullanıcılar zamanlama, voltaj, frekans ayarlarını kolayca girebiliyor. Saf alüminyumdan yapılmış ısı dağıtıcısı daha hızlı ısı dağılımı sağlarken sekiz-katmanlı PCB ısıyı yönetmeye yardımcı olur ve üstün overclock imkanı tanır.", Price =160 , Stock =500 , IsApproved = true, CategoryId = 4, Image="18.jpg" },
            new Product() { Name = "Corsair (32x2) Ram", Description = "4000Mz Cl 16 Vengeance LPX DDR bellek serisi yüksek performanslı overclock için tasarlanmıştır. DR4 bellekler yüksek hız yanında düşük güç tüketimi ön plana çıkıyor. Asus, MSI, ASRock, Gigabyte gibi anakart üreticilerinin test edip onay verdiği yeni seriler XMP 2.0 profili içeriyor. Böylece kullanıcılar zamanlama, voltaj, frekans ayarlarını kolayca girebiliyor. Saf alüminyumdan yapılmış ısı dağıtıcısı daha hızlı ısı dağılımı sağlarken sekiz-katmanlı PCB ısıyı yönetmeye yardımcı olur ve üstün overclock imkanı tanır.", Price =300 , Stock =500 , IsApproved = true, CategoryId = 4, Image="19.jpg" },
            new Product() { Name = "Corsair (32x4) Ram", Description = "5000MZ cl 16 Vengeance LPX DDR bellek serisi yüksek performanslı overclock için tasarlanmıştır. DR4 bellekler yüksek hız yanında düşük güç tüketimi ön plana çıkıyor. Asus, MSI, ASRock, Gigabyte gibi anakart üreticilerinin test edip onay verdiği yeni seriler XMP 2.0 profili içeriyor. Böylece kullanıcılar zamanlama, voltaj, frekans ayarlarını kolayca girebiliyor. Saf alüminyumdan yapılmış ısı dağıtıcısı daha hızlı ısı dağılımı sağlarken sekiz-katmanlı PCB ısıyı yönetmeye yardımcı olur ve üstün overclock imkanı tanır.", Price =500 , Stock =500 , IsApproved = true, CategoryId = 4, Image="20.jpg" },


            new Product() { Name = "Asus B350 Motherboard", Description = "Intel Soket M.2 desteği, HDMI/DVI-D/D-Sub, SATA 6 Gbps, 1 Gb Ethernet, USB 3.2 Gen 1 Type-A ve BIOS FlashBack™ özelliklerine sahip micro ATX anakart", Price =500 , Stock =500 , IsApproved = true, CategoryId = 5, Image="21.jpg" },
            new Product() { Name = "Asus B350 Plus Motherboard", Description = "Intel Soket M.2 desteği, HDMI/DVI-D/D-Sub, SATA 6 Gbps, 1 Gb Ethernet, USB 3.2 Gen 1 Type-A ve BIOS FlashBack™ özelliklerine sahip micro ATX anakart", Price =600 , Stock =500 , IsApproved = true, CategoryId = 5, Image="22.jpg" },
            new Product() { Name = "Asus B450 Motherboard", Description = "Intel Soket M.2 desteği, HDMI/DVI-D/D-Sub, SATA 6 Gbps, 1 Gb Ethernet, USB 3.2 Gen 1 Type-A ve BIOS FlashBack™ özelliklerine sahip micro ATX anakart", Price =700 , Stock =500 , IsApproved = true, CategoryId = 5, Image="23.jpg" },
            new Product() { Name = "Asus B450 Plus Motherboard", Description = "Intel Soket M.2 desteği, HDMI/DVI-D/D-Sub, SATA 6 Gbps, 1 Gb Ethernet, USB 3.2 Gen 1 Type-A ve BIOS FlashBack™ özelliklerine sahip micro ATX anakart", Price =750 , Stock =500 , IsApproved = true, CategoryId = 5, IsHome = true, Image="24.jpg" },
            new Product() { Name = "Asus B550 Motherboard", Description = "Intel Soket M.2 desteği, HDMI/DVI-D/D-Sub, SATA 6 Gbps, 1 Gb Ethernet, USB 3.2 Gen 1 Type-A ve BIOS FlashBack™ özelliklerine sahip micro ATX anakart", Price =1000 , Stock =500 , IsApproved = true, CategoryId = 5, Image="25.jpg" },


            new Product() { Name = "Samsung 256Gb M.2 Ssd Storage", Description = "En yüksek performans şimdi daha da gelişmiş durumda. 970 EVO’dan daha yüksek bir hıza sahip olan 970 EVO Plus, en son V-NAND teknolojisi ve aygıt yazılımı optimizasyonuyla destekleniyor ve NVMe bant genişliğinin potansiyelinden yararlanarak rakipsiz bilgi işlem gücü sağlıyor. 2TB’a kadar farklı kapasite seçeneği ve 1200 TBW’ya kadar güvenilir çalışma. Write: 2000Mb Read: 1000Mb", Price =100 , Stock =500 , IsApproved = true, CategoryId = 6, Image="26.jpg" },
            new Product() { Name = "Samsung 512Gb M.2 Ssd Storage", Description = "En yüksek performans şimdi daha da gelişmiş durumda. 970 EVO’dan daha yüksek bir hıza sahip olan 970 EVO Plus, en son V-NAND teknolojisi ve aygıt yazılımı optimizasyonuyla destekleniyor ve NVMe bant genişliğinin potansiyelinden yararlanarak rakipsiz bilgi işlem gücü sağlıyor. 2TB’a kadar farklı kapasite seçeneği ve 1200 TBW’ya kadar güvenilir çalışma. Write: 2500Mb Read: 1500Mb", Price =200 , Stock =500 , IsApproved = true, CategoryId = 6, Image="27.jpg" },
            new Product() { Name = "Samsung 1Tb M.2 Ssd Storage", Description = "En yüksek performans şimdi daha da gelişmiş durumda. 970 EVO’dan daha yüksek bir hıza sahip olan 970 EVO Plus, en son V-NAND teknolojisi ve aygıt yazılımı optimizasyonuyla destekleniyor ve NVMe bant genişliğinin potansiyelinden yararlanarak rakipsiz bilgi işlem gücü sağlıyor. 2TB’a kadar farklı kapasite seçeneği ve 1200 TBW’ya kadar güvenilir çalışma. Write: 3000Mb Read: 2000Mb", Price =500 , Stock =500 , IsApproved = true, CategoryId = 6, IsHome = true, Image="28.jpg" },
            new Product() { Name = "Samsung 1,5Tb M.2 Ssd Storage", Description = "En yüksek performans şimdi daha da gelişmiş durumda. 970 EVO’dan daha yüksek bir hıza sahip olan 970 EVO Plus, en son V-NAND teknolojisi ve aygıt yazılımı optimizasyonuyla destekleniyor ve NVMe bant genişliğinin potansiyelinden yararlanarak rakipsiz bilgi işlem gücü sağlıyor. 2TB’a kadar farklı kapasite seçeneği ve 1200 TBW’ya kadar güvenilir çalışma. Write: 3500Mb Read: 3000Mb", Price =600 , Stock =500 , IsApproved = true, CategoryId = 6, Image="29.jpg" },
            new Product() { Name = "Samsung 2Tb M.2 Ssd Storage", Description = "En yüksek performans şimdi daha da gelişmiş durumda. 970 EVO’dan daha yüksek bir hıza sahip olan 970 EVO Plus, en son V-NAND teknolojisi ve aygıt yazılımı optimizasyonuyla destekleniyor ve NVMe bant genişliğinin potansiyelinden yararlanarak rakipsiz bilgi işlem gücü sağlıyor. 2TB’a kadar farklı kapasite seçeneği ve 1200 TBW’ya kadar güvenilir çalışma. Write: 4000Mb Read: 4000Mb", Price =800 , Stock =500 , IsApproved = true, CategoryId = 6, Image="30.jpg" },


            new Product() { Name = "Seagate 500Gb Hdd Storage", Description = "BarraCuda, masaüstü ve taşınabilir bilgisayarlar için en yüksek kapasitelerle endüstride öncü konumdadır. 10 TB kapasiteye kadar disklerle, BarraCuda portföyü, her fiyat düzeyinde harika bir yükseltme seçeneğidir. Taviz vermeyen BarraCuda Pro, oyun veya ağır iş yüklerinde hızlı performans ve yükleme süreleri için sektör lideri 7200 devir/dakikalık disk hızıyla birleşiyor. Write: 500Mb Read: 300Mb", Price =30 , Stock =500 , IsApproved = true, CategoryId = 7, Image="31.jpg" },
            new Product() { Name = "Seagate 1Tb Hdd Storage", Description = "BarraCuda, masaüstü ve taşınabilir bilgisayarlar için en yüksek kapasitelerle endüstride öncü konumdadır. 10 TB kapasiteye kadar disklerle, BarraCuda portföyü, her fiyat düzeyinde harika bir yükseltme seçeneğidir. Taviz vermeyen BarraCuda Pro, oyun veya ağır iş yüklerinde hızlı performans ve yükleme süreleri için sektör lideri 7200 devir/dakikalık disk hızıyla birleşiyor. Write: 500Mb Read: 300Mb", Price =50 , Stock =500 , IsApproved = true, CategoryId = 7, Image="32.jpg" },
            new Product() { Name = "Seagate 500Gb Hdd Storage", Description = "BarraCuda, masaüstü ve taşınabilir bilgisayarlar için en yüksek kapasitelerle endüstride öncü konumdadır. 10 TB kapasiteye kadar disklerle, BarraCuda portföyü, her fiyat düzeyinde harika bir yükseltme seçeneğidir. Taviz vermeyen BarraCuda Pro, oyun veya ağır iş yüklerinde hızlı performans ve yükleme süreleri için sektör lideri 7200 devir/dakikalık disk hızıyla birleşiyor. Write: 1000Mb Read: 500Mb", Price =70 , Stock =500 , IsApproved = true, CategoryId = 7, IsHome = true, Image="33.jpg" },
            new Product() { Name = "Seagate 1Tb Hdd Storage", Description = "BarraCuda, masaüstü ve taşınabilir bilgisayarlar için en yüksek kapasitelerle endüstride öncü konumdadır. 10 TB kapasiteye kadar disklerle, BarraCuda portföyü, her fiyat düzeyinde harika bir yükseltme seçeneğidir. Taviz vermeyen BarraCuda Pro, oyun veya ağır iş yüklerinde hızlı performans ve yükleme süreleri için sektör lideri 7200 devir/dakikalık disk hızıyla birleşiyor. Write: 1000Mb Read: 500Mb", Price =80 , Stock =500 , IsApproved = true, CategoryId = 7, Image="34.jpg" },
            new Product() { Name = "Seagate 2Tb Hdd Storage", Description = "BarraCuda, masaüstü ve taşınabilir bilgisayarlar için en yüksek kapasitelerle endüstride öncü konumdadır. 10 TB kapasiteye kadar disklerle, BarraCuda portföyü, her fiyat düzeyinde harika bir yükseltme seçeneğidir. Taviz vermeyen BarraCuda Pro, oyun veya ağır iş yüklerinde hızlı performans ve yükleme süreleri için sektör lideri 7200 devir/dakikalık disk hızıyla birleşiyor. Write: 1500Mb Read: 1000Mb", Price =120 , Stock =500 , IsApproved = true, CategoryId = 7, Image="35.jpg" },


            new Product() { Name = "Cooler Master V1 Computer cooler", Description = "Çeşitli materyallere dayanıklı yapıdaki pompa ısıdan ve nemden etkilenmez. Düşük profil pompa hafif, oksidasyon ve korozyona karşı dayanıklıdır. 1000Rpm", Price =20 , Stock =500 , IsApproved = true, CategoryId = 8, Image="36.jpg" },
            new Product() { Name = "Cooler Master V2 Computer cooler", Description = "Çeşitli materyallere dayanıklı yapıdaki pompa ısıdan ve nemden etkilenmez. Düşük profil pompa hafif, oksidasyon ve korozyona karşı dayanıklıdır. 1500Rpm", Price =30 , Stock =500 , IsApproved = true, CategoryId = 8, Image="37.jpg" },
            new Product() { Name = "Cooler Master V3 Computer cooler", Description = "Çeşitli materyallere dayanıklı yapıdaki pompa ısıdan ve nemden etkilenmez. Düşük profil pompa hafif, oksidasyon ve korozyona karşı dayanıklıdır. 2000Rpm", Price =40 , Stock =500 , IsApproved = true, CategoryId = 8, IsHome = true, Image="38.jpg" },
            new Product() { Name = "Cooler Master V4 Computer cooler", Description = "Çeşitli materyallere dayanıklı yapıdaki pompa ısıdan ve nemden etkilenmez. Düşük profil pompa hafif, oksidasyon ve korozyona karşı dayanıklıdır. 2500Rpm", Price =50 , Stock =500 , IsApproved = true, CategoryId = 8, Image="39.jpg" },
            new Product() { Name = "Cooler Master V5 Computer cooler", Description = "Çeşitli materyallere dayanıklı yapıdaki pompa ısıdan ve nemden etkilenmez. Düşük profil pompa hafif, oksidasyon ve korozyona karşı dayanıklıdır. 3000Rpm", Price =60 , Stock =500 , IsApproved = true, CategoryId = 8, Image="40.jpg" },


            new Product() { Name = "Cooler Master 300W Power supply", Description = "MWE Bronze serisi, sisteminizi düşük maliyetle güvenli ve verimli bir şekilde çalıştırmak için güvenilir bir yol sunar. 80 PLUS Bronze verimlilik sertifikası, DC-DC + LLC devre tasarımı, +12V tek kanal çıkışı, aktif PFC koruması ve sıcaklığa duyarlı HDB fanı, orijinal ve amacına uygun bir güç kaynağı performansı sunar. MWE Bronze serisi ihtiyaçlarınızın neredeyse tamamına yanıt vermek için özel olarak tasarlandı.", Price =30 , Stock =500 , IsApproved = true, CategoryId = 9, Image="41.jpg" },
            new Product() { Name = "Cooler Master 400W Power supply", Description = "MWE Bronze serisi, sisteminizi düşük maliyetle güvenli ve verimli bir şekilde çalıştırmak için güvenilir bir yol sunar. 80 PLUS Bronze verimlilik sertifikası, DC-DC + LLC devre tasarımı, +12V tek kanal çıkışı, aktif PFC koruması ve sıcaklığa duyarlı HDB fanı, orijinal ve amacına uygun bir güç kaynağı performansı sunar. MWE Bronze serisi ihtiyaçlarınızın neredeyse tamamına yanıt vermek için özel olarak tasarlandı.", Price =50 , Stock =500 , IsApproved = true, CategoryId = 9, Image="42.jpg" },
            new Product() { Name = "Cooler Master 500W Power supply", Description = "MWE Bronze serisi, sisteminizi düşük maliyetle güvenli ve verimli bir şekilde çalıştırmak için güvenilir bir yol sunar. 80 PLUS Bronze verimlilik sertifikası, DC-DC + LLC devre tasarımı, +12V tek kanal çıkışı, aktif PFC koruması ve sıcaklığa duyarlı HDB fanı, orijinal ve amacına uygun bir güç kaynağı performansı sunar. MWE Bronze serisi ihtiyaçlarınızın neredeyse tamamına yanıt vermek için özel olarak tasarlandı.", Price =70 , Stock =500 , IsApproved = true, CategoryId = 9, Image="43.jpg" },
            new Product() { Name = "Cooler Master 600W Power supply", Description = "MWE Bronze serisi, sisteminizi düşük maliyetle güvenli ve verimli bir şekilde çalıştırmak için güvenilir bir yol sunar. 80 PLUS Bronze verimlilik sertifikası, DC-DC + LLC devre tasarımı, +12V tek kanal çıkışı, aktif PFC koruması ve sıcaklığa duyarlı HDB fanı, orijinal ve amacına uygun bir güç kaynağı performansı sunar. MWE Bronze serisi ihtiyaçlarınızın neredeyse tamamına yanıt vermek için özel olarak tasarlandı.", Price =80 , Stock =500 , IsApproved = true, CategoryId = 9, IsHome = true, Image="44.jpg" },
            new Product() { Name = "Cooler Master 1000W Power supply", Description = "MWE Bronze serisi, sisteminizi düşük maliyetle güvenli ve verimli bir şekilde çalıştırmak için güvenilir bir yol sunar. 80 PLUS Bronze verimlilik sertifikası, DC-DC + LLC devre tasarımı, +12V tek kanal çıkışı, aktif PFC koruması ve sıcaklığa duyarlı HDB fanı, orijinal ve amacına uygun bir güç kaynağı performansı sunar. MWE Bronze serisi ihtiyaçlarınızın neredeyse tamamına yanıt vermek için özel olarak tasarlandı.", Price =130 , Stock =500 , IsApproved = true, CategoryId = 9, Image="45.jpg" },


            new Product() { Name = "Computer tower V1", Description = "Poligonal Mesh Tasarım, Kristalize Temperli Cam Panel, 4x120MM Adreslenebilir RGB Fan, Çift 360mm Radyatör Desteği, Çok Yönlü Soğutma 2X Fan", Price =50 , Stock =500 , IsApproved = true, CategoryId = 10, Image="46.jpg" },
            new Product() { Name = "Computer tower V2", Description = "Poligonal Mesh Tasarım, Kristalize Temperli Cam Panel, 4x120MM Adreslenebilir RGB Fan, Çift 360mm Radyatör Desteği, Çok Yönlü Soğutma 3X Fan", Price =70 , Stock =500 , IsApproved = true, CategoryId = 10, Image="47.jpg" },
            new Product() { Name = "Computer tower V3", Description = "Poligonal Mesh Tasarım, Kristalize Temperli Cam Panel, 4x120MM Adreslenebilir RGB Fan, Çift 360mm Radyatör Desteği, Çok Yönlü Soğutma 4X Fan", Price =90 , Stock =500 , IsApproved = true, CategoryId = 10, Image="48.jpg" },
            new Product() { Name = "Computer tower V4", Description = "Poligonal Mesh Tasarım, Kristalize Temperli Cam Panel, 4x120MM Adreslenebilir RGB Fan, Çift 360mm Radyatör Desteği, Çok Yönlü Soğutma 5X Fan", Price =120 , Stock =500 , IsApproved = true, CategoryId = 10, Image="49.jpg" },
            new Product() { Name = "Computer tower V5", Description = "Poligonal Mesh Tasarım, Kristalize Temperli Cam Panel, 4x120MM Adreslenebilir RGB Fan, Çift 360mm Radyatör Desteği, Çok Yönlü Soğutma 6X Fan", Price =160 , Stock =500 , IsApproved = true, CategoryId = 10, Image="50.jpg" },

        };

            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }

            context.SaveChanges();
            base.Seed(context);
        }
    }
}
